// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsX-aEdrbtVLEZ9yRYLNyrkm6YAYt10S4',
    appId: '1:915621401033:web:e84d12f5363ca6f5829818',
    messagingSenderId: '915621401033',
    projectId: 'medrecs-ae89b',
    authDomain: 'medrecs-ae89b.firebaseapp.com',
    storageBucket: 'medrecs-ae89b.appspot.com',
    measurementId: 'G-05MMQHDDTQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrxqFeQOGe2mAjBxILSzF3oj9ffSYMyw4',
    appId: '1:915621401033:android:5be04ccfb499a9aa829818',
    messagingSenderId: '915621401033',
    projectId: 'medrecs-ae89b',
    storageBucket: 'medrecs-ae89b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCildK4HxZtjiHoEsYKwUPRGAaJVaivA8U',
    appId: '1:915621401033:ios:f5c01ba98202bb95829818',
    messagingSenderId: '915621401033',
    projectId: 'medrecs-ae89b',
    storageBucket: 'medrecs-ae89b.appspot.com',
    iosBundleId: 'com.example.medrecs',
  );
}
